Update expression.yaml

diff --git a/.github/workflows/expression.yaml b/.github/workflows/expression.yaml
--- a/.github/workflows/expression.yaml
+++ b/.github/workflows/expression.yaml
@@ -11,7 +11,7 @@ on:
           - 'yes'
           - 'no'
 env:
-  TEST_ENV: ${{ inputs.isPass == 'yes' }}
+  IS_PASS_ENV: ${{ inputs.isPass == 'yes' }}
 
 jobs:
   yes-job:
@@ -21,11 +21,19 @@ jobs:
       - name: print input when yes
         run: echo "The value is ${{ inputs.isPass }}"
         
-      - name: printe nv from bash
-        run: echo "TEST ENV is $TEST_ENV"
+      - name: printe env from bash
+        run: echo "TEST ENV is $IS_PASS_ENV"
   
       - name: print env
-        run: echo "The value is ${{ env.TEST_ENV }}"
+        run: echo "The value is ${{ env.IS_PASS_ENV }}"
+        
+      - name: fail job if no is the input 
+        run: |
+          echo "This fails the job. urrent input is ${{ inputs.isPass }}
+          if [[ $IS_PASS_ENV == true ]]
+          then
+            exit 1
+          fi
 
   no-job:
     if: inputs.isPass == 'no'
@@ -34,3 +42,9 @@ jobs:
       - name: print input when no
         run: echo "The value is ${{ inputs.isPass }}"
         
+  not-run-if-fail:
+    runs-on: ubuntu-latest
+    if: failure()
+    steps:
+      - run: echo "The job has now failed"
+    
